### PR TITLE
Add time and timezone to updateTo date

### PR DESCRIPTION
**Pull request by cinlloc**
#73 An issue in UForge 3.6 lead to change date format in order to handle time and timezone information. Documentation has to be fixed in consequence.

### CODE REVIEW

**Comment by cinlloc** [comment]
May be other docs impacted: https://github.com/usharesoft/hammr/search?utf8=%E2%9C%93&q=updateTo

**Comment by jbremond** [comment]
Hello,

Thanks for this pull request. We need the documentation update in the same pull request.
Thanks in advance.

Regards,
Joris

**Comment by jbremond** [comment]
I was wrong in my last comment. We need to check all pointers send by @cinlloc and check if we need to update it. We need the help of @emuus.

Regards,
Joris

**Comment by emuus** [comment]
the changes proposed by Clement are fine by me !

**Comment by jbremond** [comment]
Thanks @emuus for your return. 
Regarding the potential docs impacts, do you think we need to update it ?

Thanks in advance.
Joris

**Comment by jbremond** [comment]
Ok I will merge the pull request with current modifications.
Thanks

Regards,
Joris

**Pull request merged**
